### GET "Hello word"
GET http://localhost:8080/api/message

### GET podructos
GET http://localhost:8080/api/v1/productos

### GET podructos by Id
GET http://localhost:8080/api/v1/productos/1


### POST guardar un producto
POST http://localhost:8080/api/v1/productos
content-type: application/json

{
  "id": null,
  "nombre": "Zapatilla HANDBALL SPEZIAL",
  "descripcion": "La zapatilla favorita de los profesionales del balonmano en 1979 triunfa hoy en las calles gracias a su estilo atemporal. Esta versión presenta una parte superior de nobuk muy suave al tacto.",
  "precio": 110,
  "cantidadStock": 100,
  "genero": "Masculino",
  "tallas": [3],
  "colores": [3, 4], 
  "categoria": 3
}