### GET "Hello word"
GET http://localhost:8080/api/message

### GET podructos
GET http://localhost:8080/api/v1/products

### GET podructos by Id
GET http://localhost:8080/api/v1/products/8


### POST guardar un producto
POST http://localhost:8080/api/v1/products
content-type: application/json

{
  "name": "Zapatillas Spezial",
  "description": "La zapatilla favorita de los profesionales del balonmano en 1979.",
  "price": 110,
  "stockQuantity": 100,
  "gender": "Male",
  "sizesIds": [3],
  "colorsIds": [3, 4], 
  "categoryId": 3,
  "brandId": 1
}