spring:
  application:
    name: examples
  datasource:
    url: jdbc:mysql://localhost:3306/api_fake
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Lpk9m1iw
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
